optifund:
  outputs:
    dev:
      dataset: project_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\Yann\OptiFund-Data-Driven-Portfolio-Optimization\terraform\keys\my-creds.json
      location: EU
      method: service-account
      priority: interactive
      project: dtc-de-project-454412
      threads: 1
      type: bigquery
  target: dev
