tickers: ["AAPL", "GOOGL", "MSFT"]
start_date: "2023-01-01"
end_date: "2023-12-31"
storage_bucket: "your-gcs-bucket"

# fetch_data.yaml (Kestra workflow example)
id: fetch_stock_data
namespace: stock_analysis

inputs:
  tickers:
    type: list
    required: true

steps:
  - id: fetch
    type: io.kestra.plugin.scripts.python.Python
    script: |
      from data_ingestion.fetch_data import fetch_stock_data
      
      tickers = {{ inputs.tickers }}
      data = fetch_stock_data(tickers, "2023-01-01", "2023-12-31")
      print(data.head())